# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aishiftscheduler',
                'doc_host': 'https://LearnableLoopAI.github.io',
                'git_url': 'https://github.com/LearnableLoopAI/aishiftscheduler',
                'lib_path': 'aishiftscheduler'},
  'syms': {'aishiftscheduler.core': {'aishiftscheduler.core.foo': ('core.html#foo', 'aishiftscheduler/core.py')}}}
