# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_dbmodels.ipynb.

# %% auto 0
__all__ = ['UserInput', 'User']

# %% ../nbs/13_dbmodels.ipynb 7
## models.py from tut
# from aishiftscheduler.production import Base
from .database import Base
from sqlalchemy import Column, Integer, String
from sqlalchemy.sql.expression import text
from sqlalchemy.sql.sqltypes import TIMESTAMP

# %% ../nbs/13_dbmodels.ipynb 8
class UserInput(Base):
    __tablename__ = "userinputs"

    id = Column(Integer, primary_key=True, nullable=False)
    start = Column(String, nullable=False)
    slots_per_day = Column(Integer, nullable=False)
    max_daily_slot_run = Column(Integer, nullable=False)
    resources = Column(String, nullable=False)
    demands_per_busyness = Column(String, nullable=False)
    demands_per_volume = Column(String, nullable=False)
    demands_per_revenue = Column(String, nullable=False)
    resource_expenses = Column(String, nullable=False)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=text('now()'))

# %% ../nbs/13_dbmodels.ipynb 9
class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, nullable=False)
    email = Column(String, nullable=False, unique=True)
    password = Column(String, nullable=False)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=text('now()'))
