# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_loader.ipynb.

# %% auto 0
__all__ = ['load_sick_probs', 'load_merit_probs', 'load_exog_info']

# %% ../nbs/01_loader.ipynb 4
import pandas as pd

# %% ../nbs/01_loader.ipynb 7
def load_sick_probs(filename):
  sick_df = pd.read_excel(
      filename,
      sheet_name='SickProbs',
      ## skiprows=3,
      converters={'ResourceId':str}
      )
  return sick_df

# %% ../nbs/01_loader.ipynb 8
def load_merit_probs(filename):
  merit_df = pd.read_excel(
      filename,
      sheet_name='MeritProbs',
      ## skiprows=3,
      converters={'ResourceId':str}
      )
  return merit_df

# %% ../nbs/01_loader.ipynb 9
def load_exog_info(filename):
  exog_info_df = pd.read_excel(
    filename,
    sheet_name='ExogInfo2',
    skiprows=6,
    converters={'volume':int}
    )
  return exog_info_df
