# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/17_oauth2.ipynb.

# %% auto 0
__all__ = ['SECRET_KEY', 'ALGORITHM', 'ACCESS_TOKEN_EXPIRE_MINUTES', 'create_access_token']

# %% ../nbs/17_oauth2.ipynb 6
from jose import JWTError, jwt
from datetime import datetime, timedelta

# import aishiftscheduler.dbmodels as dbm
# import aishiftscheduler.schemas as sch
# import aishiftscheduler.utils as utl
# from aishiftscheduler.database import get_db

# %% ../nbs/17_oauth2.ipynb 7
## SECRET_KEY
## Algorithm
## Expiration time

SECRET_KEY = "change me by going to oauth2 docs and get longer one"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

def create_access_token(data: dict):
    to_encode = data.copy()

    expire = datetime.now() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire})

    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

    return encoded_jwt
