# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_schemas.ipynb.

# %% auto 0
__all__ = ['UserInputBase', 'UserInputCreate', 'UserInputUpdate', 'UserInput', 'UserCreate', 'UserOut', 'UserLogin']

# %% ../nbs/14_schemas.ipynb 7
from pydantic import BaseModel, EmailStr
from datetime import datetime

# %% ../nbs/14_schemas.ipynb 8
class UserInputBase(BaseModel):
    start: str
    slots_per_day: int
    max_daily_slot_run: int
    resources: str
    demands_per_busyness: str
    demands_per_volume: str
    demands_per_revenue: str
    resource_expenses: str

# %% ../nbs/14_schemas.ipynb 9
class UserInputCreate(UserInputBase):
    pass

# %% ../nbs/14_schemas.ipynb 10
class UserInputUpdate(UserInputBase):
    pass

# %% ../nbs/14_schemas.ipynb 11
## response model
class UserInput(UserInputBase):
    id: int
    created_at: datetime

    class Config:
        orm_mode = True

# %% ../nbs/14_schemas.ipynb 12
class UserCreate(BaseModel):
    email: EmailStr
    password: str

# %% ../nbs/14_schemas.ipynb 13
class UserOut(BaseModel):
    id: int
    email: EmailStr
    created_at: datetime

    class Config:
        orm_mode = True

# %% ../nbs/14_schemas.ipynb 14
class UserLogin(BaseModel):
    email: EmailStr
    password: str
